openapi: 3.0.3
info:
  title: API structure components schema
  version: 1.0.0
servers:
  - url: 'http://localhost:8000'
paths:
  /tasks:
    get:
      summary: List of all the tasks
      responses:
        200:
          description: List of tasks
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Task'
    post:
      summary: create a new list of tasks
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: array
              items:
                $ref: '#/components/schemas/Task'
      responses:
        201:
          description: Task created
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Task'

    delete:
      summary: delete task
      requestBody:
        content:
          application/json:
            schema:
              type: array
              items:
                type: object
                properties:
                  taskIdentifier:
                    type: integer
      responses:
        200:
          description: List of deleted tasks
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Task'
  /tasks/{id}:
    get:
      summary: Return tasks by id
      parameters:
        - in: path
          name: id
          required: true
          schema:
            type: integer
      responses:
        '200':
          description: Task found
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Task'
        '404':
          description: Task
          content:
            text/plain:
              schema:
                type: string
                example: Task not found
    delete:
      parameters:
        - in: path
          name: id
          required: true
          schema:
            type: integer
      responses:
        '200':
          description: Task deleted
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Task'
        '404':
          description: Task not found
          content:
            text/plain:
              schema:
                type: string
                example: Task not found

  components:
    schemas:
      Task:
        type: object
        properties:
          id:
            type: integer
            example: 1
          title:
            type: string
            example: Faire les courses
          completed:
            type: boolean
            example: false
        required:
          - id
          - title
          - completed





